### Send POST request with json body
POST http://localhost:8080/create-developer
Content-Type: application/json

{
  "developerLevel": "SENIOR",
  "developerSkillType": "BACK_END",
  "experienceYears": 12,
  "memberId": "Mini",
  "name": "mouse",
  "age": 20
}